/* Generated by Yosys 0.27+22 (git sha1 53c0a6b78, aarch64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(ovf, clk, rst, en);
  reg \$auto$verilog_backend.cc:2097:dump_module$2  = 0;
  (* src = "/Users/fischerm/splat/up_counter.py:34" *)
  wire \$1 ;
  (* src = "/Users/fischerm/splat/up_counter.py:40" *)
  wire [16:0] \$3 ;
  (* src = "/Users/fischerm/splat/up_counter.py:40" *)
  wire [16:0] \$4 ;
  (* src = "/Users/fischerm/Library/Python/3.9/lib/python/site-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/Users/fischerm/splat/up_counter.py:29" *)
  reg [15:0] count = 16'h0000;
  (* src = "/Users/fischerm/splat/up_counter.py:29" *)
  reg [15:0] \count$next ;
  (* src = "/Users/fischerm/splat/up_counter.py:25" *)
  input en;
  wire en;
  (* src = "/Users/fischerm/splat/up_counter.py:26" *)
  output ovf;
  wire ovf;
  (* src = "/Users/fischerm/Library/Python/3.9/lib/python/site-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  assign \$1  = count == (* src = "/Users/fischerm/splat/up_counter.py:34" *) 5'h19;
  assign \$4  = count + (* src = "/Users/fischerm/splat/up_counter.py:40" *) 1'h1;
  always @(posedge clk)
    count <= \count$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$2 ) begin end
    \count$next  = count;
    (* src = "/Users/fischerm/splat/up_counter.py:36" *)
    casez (en)
      /* src = "/Users/fischerm/splat/up_counter.py:36" */
      1'h1:
          (* full_case = 32'd1 *)
          (* src = "/Users/fischerm/splat/up_counter.py:37" *)
          casez (ovf)
            /* src = "/Users/fischerm/splat/up_counter.py:37" */
            1'h1:
                \count$next  = 16'h0000;
            /* src = "/Users/fischerm/splat/up_counter.py:39" */
            default:
                \count$next  = \$4 [15:0];
          endcase
    endcase
    (* src = "/Users/fischerm/Library/Python/3.9/lib/python/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \count$next  = 16'h0000;
    endcase
  end
  assign \$3  = \$4 ;
  assign ovf = \$1 ;
endmodule
