name: run_tests
on: [push]
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install from source
        run: python3 -m pip install .[dev]

      - name: Run tests
        run: make test